version: '3.9'
services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=netwitness
      - MONGO_INITDB_DATABASE=pubg
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - pubg-mongo:/data
    ports:
      - '27017:27017'

volumes:
  pubg-mongo:
    external: true
